spring.application.name=TFG
server.port=${PORT}

# --- Base de datos ---
spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASS}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=${DDLAUTO}
spring.jpa.show-sql=${SHOWSQL}
spring.jpa.properties.hibernate.format_sql=${FORMATSQL}
spring.jpa.properties.hibernate.dialect=${DIALECT}
spring.jpa.database-platform=${DB_DIALECT}

# --- JWT ---
jwt.secret=${JWTKEY}
jwt.expiration-ms=${JWTEXP}

# --- App ---
app.frontend.url=${FRONTURL}
